[package]
name = "warp-packer"
version = "0.3.0"
authors = ["Diego Giagio <diego@giagio.com>"]

[dependencies]
clap = "2.32.0"
dirs = "3.0.0"
reqwest = "0.10.6"
tempdir = "0.3.7"
flate2 = "1.0"
tar = "0.4"
lazy_static = "1.1.0"