name: clean artifacts

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        uses: glassechidna/artifact-cleaner@v2
        with:
          minimumAge: 86400 # all artifacts at least one day old
